version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.19.4"
replacements:
  group: "dev.tr7zw"
  name: "Exordium"
  id: "exordium"
  version: "1.0.3"
  author: "tr7zw"
  dependencies: ""
  relocationpackage: "dev.tr7zw.exordium"
  licensename: "LICENSE"
  modrinthid: "DynYZEae"
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  FG-Fabric:
    template: "Fabric"
