version: '0.0.2'
source: "https://github.com/tr7zw/ProcessedModTemplate/tree/master"
replacements:
  name: "Exordium"
  id: "exordium"
  version: "2.0.0"
  description: "Renders the UI at a lower framerate to give the gameplay more legroom."
  homepageUrl: "https://modrinth.com/mod/exordium"
  sourcesUrl: "https://github.com/tr7zw/Exordium"
  issuesUrl: "https://github.com/tr7zw/Exordium/issues"
  fabric_entrypoint: "dev.tr7zw.exordium.ExordiumMod"
  fabric_modmenu_entrypoint: "dev.tr7zw.exordium.ExordiumModMenu"
  relocationpackage: "dev.tr7zw.exordium"
  licensename: "LICENSE-Exordium"
  modrinthid: DynYZEae
  curseforgeid: 681953
  versionlessname: "Exordium-Versionless"
  fabric_dependencies: "
    modCompileOnly 'maven.modrinth:xaeros-minimap:25.2.12_Fabric_1.21.8'\n
    "
  forge_dependencies: "
    modCompileOnly 'maven.modrinth:xaeros-minimap:25.2.12_Forge_1.20.6'\n
    "
  neoforge_dependencies: "
    modCompileOnly 'maven.modrinth:xaeros-minimap:25.2.12_NeoForge_1.21.8'\n
    "
enabledFlags:
  - autopublish
  - publishFabric
  - modrinth
  - curseforge
  - versionless
  - includeLibs
  - addTRansitionLib
  - addTRenderLib
  - mixinextras
rootProject:
  template: "."
subProjects:
  Exordium-Versionless:
    template: "Versionless"
    replacements:
      dependencies: '

      compileOnly "com.google.code.gson:gson:2.10.1"

      compileOnly "org.apache.logging.log4j:log4j-core:2.20.0"
      '